### ISSUE TITLE
Content Organization in 0.9.12

### ISSUE THREAD

**Issue by Zitchas** [robot-rover/endless-sky-viewer#1]
First off, thanks for making this! It is a useful tool for looking through ships, checking out the calculated values, and building variants. I think this will be quite valuable going forward.

One thing I noticed, however, is that it doesn't seem to handle using my GitHub-managed install. If I point the application to my steam install of endless-sky, it works fine. If I point it ad my GitHub managed install, it gets stuck at about the 90% mark and doesn't move forward, ever. My suspicion is that this is due to the re-organization that took place in 0.9.12. Namely, all the data files have been sorted into folders. So there is a Remnant folder, a Quarg folder, a Human folder, etc. They are still all inside the data folder, just with an extra layer of sorting.

**Comment by robot-rover** [comment]
Yeah, that would be it. The last 10% of the bar is loading the data files (the first 90% is sprites). I'll look into it.

**Comment by Zitchas** [comment]
Is it looking for specific files within the data folder, or just parsing everything in it? I tried just relocating all the files out of the folders back into the data folder, and it still locks up at 90%...

**Comment by robot-rover** [comment]
Fixed in https://github.com/robot-rover/endless-sky-viewer/commit/aae88970c7bf32f1616fab72f3f7584368272ce4

**Comment by Zitchas** [comment]
Thank you!
