### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by Zitchas** [robot-rover/endless-sky-viewer#3]
Within Endless-Sky, the world is basically black. All the ship and outfit thumbnails are displayed on an almost black background. As such, when displayed on a white background they look almost like silhouettes. As such, it would be much appreciated if there was a way to view the ships with a dark background, similar to what we see in the Shipyard/Outfitter.

Related to that, having a dark mode color scheme would be easier on the eyes, so having one would be much appreciated.

Thanks!

**Comment by robot-rover** [comment]
Added w/ https://github.com/robot-rover/endless-sky-viewer/commit/03994c8557f17cb9bc2cafcc420401a4a17168dd
