### ISSUE TITLE
Request: Max Speed, Acceleration, and Turn Speed

### ISSUE THREAD

**Issue by Zitchas** [robot-rover/endless-sky-viewer#4]
Would it be possible to have the ship info panel show Max Speed, Acceleration, and Turn Speed? These are the values that people are used to seeing in-game; and generally the useful values that people think about in comparing ships.

I'm sure you already know the formula, but just for reference:

> thrust / mass = acceleration
> thrust / drag = max speed
> turn / mass = turn rate

On a related note, would it be possible to have the thrust and turning things gathered together? I just took a look at the Ibis, for instance, and noted that the turn related values are the 1st, 4th, and 5th lines. Thrust info is on lines 8th and 17th. And drag is on line 15. Which is scattered all over the place, and kind of hard to easily browse.

**Comment by robot-rover** [comment]
Solved by cae47fd3908a0b6e7f33eafd750f0e61b8d165b0
